name: Minify Workflow
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: ${{ github.ref }}

        - name: Auto Minify
          uses: nizarmah/auto-minify@v2.1
          with:
            overwrite: true

        # Auto commits minified content to the existing files
        # Ignore it if you don't want to commit the files to the repository 
        - name: Commit
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "Github Action: Auto Minified JS and CSS files"
            branch: production
