name: Minify Workflow
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: ${{ github.ref }}

        - name: Auto Minify
          uses: nizarmah/auto-minify@v2.1.1
          with:
            overwrite: true
            js_engine: uglify-js

        - name: Delete old production branch
          uses: dawidd6/action-delete-branch@v3.1.0
          with:
            branches: production

        - name: Commit
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "Github Action: Auto Minified JS and CSS files"
            branch: production
            create_branch: true