name: Auto Minify
on:
  push:
    branches: [ main ]
jobs:
  auto-minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nizarmah/auto-minify@v1.0.0
        with:
          directory: '.'
          output: 'production'
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add production/*
          git commit -m "Auto Minify" || echo "No changes to commit"
          git push origin production
